version: '3.10'

services:
  db:
    container_name: e-commerce_app
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: user_db

    volumes:
      - ./data/db:/var/lib/mysql

    healthcheck:
      test:
       - CMD
       - mysqladmin
       - ping
       - '-p${root}'
      retries: 3
      timeout: 5s
  
  server:
    container_name: chat_server
    build: .
    working_dir: /code/app
    command: uvicorn main:app --host 0.0.0.0 --reload
    environment:
      DEBUG: 1
    volumes:
      - ./app:/code/app
    depends_on:
      - db
    ports:
      - 8008:8000
    restart: on-failure
